### ISSUE TITLE
Make JAI-EXT not dependant on JAITools

### ISSUE THREAD

**Issue by ugomos** [geosolutions-it/jai-ext#142]
In order to port along time relevant JAITools operations to JAI-EXT and eliminate the dependencies on JAITools (that is basically not supported anymore), a starting point is to make the existing JAI-EXT code not to be dependant on JAITools.

**Comment by aaime** [comment]
Is this one complete now?

**Comment by ugomos** [comment]
Yes. I am going to close it then.
