### ISSUE TITLE
Upgrade to jts-core 1.15

### ISSUE THREAD

**Issue by willcohen** [geosolutions-it/jai-ext#182]
While #162 is still unresolved, the jts-example issue mentioned there also currently prevents an upgrade to 1.15 (locationtech/jts#263), since [ExtendedCoordinate](https://github.com/geosolutions-it/jai-ext/blob/master/jt-vectorbin/src/main/java/it/geosolutions/jaiext/vectorbin/VectorBinarizeOpImage.java#L40) isn't on maven for 1.15's org.locationtech classes. Does jai-ext need those classes, and if so, should it just bundle a copy?

**Comment by jnh5y** [comment]
@willcohen As a note about upgrading jai-ext to JTS 1.15, I've got branches for jai-ext, jaitools, GeoTools, GeoWebCache, and GeoServer all hanging out...

I'm interested in sorting out things like this as we go forward with JTS.

**Comment by aaime** [comment]
@jnh5y you should probably do one (or more) proposals across the various communities to get this started. Commits/merges should be synched to avoid extended periods of the various bits not building.

**Comment by jodygarnett** [comment]
Coordinating JTS 1.15 upgrade [here](https://github.com/geotools/geotools/wiki/Upgrade-to-JTS-1.15.0) so we can manage to sync the change across related projects.

**Comment by simboss** [comment]
Is this still valid for JAI-Ext?

**Comment by aaime** [comment]
The upgrade of JTS happened already, I'm closing it.

**Comment by jodygarnett** [comment]
the resolution was not to use extended coordinate sequence, the code in question only used it as a dependency and never made use of the M information (in XYZM)
