### ISSUE TITLE
Can I use jai_codec.jar and  jai_core.jar?

### ISSUE THREAD

**Issue by joshi1976** [geosolutions-it/jai-ext#190]
In my project we are using JAI 1.1.3 for image processing but only using 2 jar files nothing else.

jai_codec.jar
 jai_core.jar

Now JAI is no longer supported so trying to find out alternative for JAI and found that JAI-ext is good choice ...but when I downloaded the jar files for this JAI-EXT I see same jar files there also.

I am confused...If JAI is no longer supported then

Can I use existing jar files in my project? if not then not sure why same jar files are included in JAI-EXT project as well?
What's the alternative for these 2 jar files?
Thank you in advance.

**Comment by aaime** [comment]
jai-ext, as the name implies, is not a replacement, but an "extension" to JAI, meaning that you also need JAI in the classpath. jai-ext replaces a number of operations, provides alternative tile cache and registry, handles the concept of NODATA, but still needs the API from JAI (and does not replace all the operations).

**Comment by joshi1976** [comment]
Ok Thanks. but Now JAI is no longer supported right? that's why I am looking for alternative and thinking I can't use these jar files now or am I missing something?
