### ISSUE TITLE
Resurrect the Jiffle language as a JAI-EXT module

### ISSUE THREAD

**Issue by aaime** [geosolutions-it/jai-ext#192]
[Jiffle](https://github.com/mbedward/jiffle) provides a great map algebra support, but the project has not seen activity in years and won't work on Java 8 (due to a variety of issues, including lack of support for Antlr3 and Janino for Java 8).

Michael has authorized us to take over the project as part of jai-ext. Actions:

- Complete the work started in the antlr4 branch, to migrate on Antlr4 and latest Janino versions
- Add extra test scripts in the mix, courtesy of Andrea Antonello
- Migrate the result as a jai-ext module, add jai-ext copyright headers on top of jiffle ones

**Comment by jericks** [comment]
I am thrilled that Jiffle is going to be supported by jai-ext!  I use it in geoscript-groovy in the MapAlgebra class:

https://github.com/geoscript/geoscript-groovy/blob/master/src/main/groovy/geoscript/layer/MapAlgebra.groovy

As soon as this gets merged and released, I will update geoscript!

Thanks Andrea!

**Comment by aaime** [comment]
@jericks we're almost there. I've made some changes in Jiffle to increase its performance (3-4 times on some simple algebraic cases) but I'm not sure if that introduced backwards compatibility issues, like, behavior wise (hopefully not API wise). So, some feedback from you would be quite useful.
